#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

FILES=$(git diff --cached --name-only --diff-filter=ACMR "*.cs" | sed 's| |\\ |g')

if [ ! -z "$FILES" ]; then
  # Format all selected files
  echo "$FILES" | dotnet format --include -
  # Add back the modified/formatted files to staging
  echo "$FILES" | xargs git add
fi

npx lint-staged
